export const ArticlesJson = [
        {
            "title": "Unable to rebuild rain-damaged house, Samba family living in undergound bunker",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/j-k/unable-to-rebuild-rain-damaged-house-samba-family-living-in-undergound-bunker-534233",
            "clean_url": "tribuneindia.com",
            "excerpt": "With guns falling silent along the India-Pakistan border in Jammu and Kashmir over the last two years, thousands of bunkers built for border residents were rendered useless.",
            "summary": "Samba/Jammu, August 11\n\nWith guns falling silent along the India-Pakistan border in Jammu and Kashmir over the last two years, thousands of bunkers built for border residents were rendered useless.\n\nBut for Samba resident Karnail Chand, one such structure has proved to be a blessing in disguise.\n\nSixty-three-year-old Chand, hailing from Nanga village near the International Border in Ramgarh sector, is using the 14x8x7 feet underground bunker as a shelter after his single-storey house collapsed over four years ago due to lack of maintenance owing to abject poverty.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_213317874.jpg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "7bbd4ac3e3858fabd5c5d84a436bd09c"
        },
        {
            "title": "Indulge in Unparalleled Luxury at Rustomjee Seasons",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/indulge-in-unparalleled-luxury-at-rustomjee-seasons-a-ready-to-move-in-gated-community20230811185518/",
            "clean_url": "aninews.in",
            "excerpt": "BusinessWire India Mumbai (Maharashtra) [India], August 11: Rustomjee, the renowned real estate developer, known for its customer-centric approach and commitment to creating a harmonious community…",
            "summary": "BusinessWire India\nMumbai (Maharashtra) [India], August 11: Rustomjee, the renowned \nreal estate developer\n, known for its customer-centric approach and commitment to creating a harmonious community living experience announced a new elevated home buying experience for its Gated Community - \nRustomjee Seasons\n. From building amenities for all age groups to keeping design thinking at the core, \nRustomjee Seasons\n is one of the most elite community living spaces in BKC.\n \nTo provide \nease of purchase\n, Rustomjee Group announced a new 25 x 4 \npayment plan\n, designed to provide an unmatched advantage to homebuyers.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/NDc0YjE4ZmUtMjc.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "927d1aefa2253ea2412e15bb90e9770b"
        },
        {
            "title": "Times Pride Fest leaves behind a Legacy of Dialogue and Collaboration for LGBTQ+ Equality",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/times-pride-fest-leaves-behind-a-legacy-of-dialogue-and-collaboration-for-lgbtq-equality20230811191222/",
            "clean_url": "aninews.in",
            "excerpt": "Mediawire New Delhi [India], August 11: As the Pride month came to a close, so did the Times Pride Fest 2023 after a fruitful run. The Times Pride Fest was a campaign that aimed at shedding light on…",
            "summary": "Mediawire\nNew Delhi [India], August 11: As the \nPride month\n came to a close, so did the \nTimes Pride Fest\n 2023 after a fruitful run. The \nTimes Pride Fest\n was a campaign that aimed at shedding light on the discrimination and injustices that are still faced by the LGBTQ+ community in India and what business owners, as well as individuals, can do to commit themselves to the cause of LGBTQ+ equality with a special onus on workplace inclusivity and DEI initiatives. The campaign was a collaborative effort between businesses such as P&G India, Godrej Capital, Senco Gold & Diamond, and The Lalit Suri Hospitality Group who have been frontrunners in the struggle to achieve workplace equality.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/OGM3ZWRhYzEtOTc.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "a3f0a582f32e682ad1fd14ec57695352"
        },
        {
            "title": "AAP MP Sushil Rinku holds unique protest, comes to Parliament shackled in chains",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/punjab/aap-mp-sushil-rinku-holds-unique-protest-comes-to-parliament-shackled-in-chains-534236",
            "clean_url": "tribuneindia.com",
            "excerpt": "The Aam Aadmi Party (AAP) MP Sushil Kumar Rinku on Friday staged a protest against the central government outside the Parliament building with his body shackled in iron chains. He raised slogans such as 'free the Parliament' and 'free the democracy'.",
            "summary": "Chandigarh, August 11\n\nThe Aam Aadmi Party (AAP) MP Sushil Kumar Rinku on Friday staged a protest against the central government outside the Parliament building with his body shackled in iron chains. He raised slogans such as 'free the Parliament' and 'free the democracy'.\n\nAddressing the mediapersons, Sushil Rinku said the central government has imprisoned the country's constitution, Parliament and law in the chains of slavery.\n\n'Today all the four pillars of the country's democracy, the legislature, the executive, the judiciary and the media are in danger,' he said.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_1996535697.jpeg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "e475ced206603dcefe55af105fb78d27"
        },
        {
            "title": "PLI For Large Scale Electronics Manufacturing Has Attracted Rs 6 887 Cr In Investments MoS Chandrasekhar",
            "author": "BW Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/PLI-For-Large-Scale-Electronics-Manufacturing-Has-Attracted-Rs-6-887-Cr-In-Investments-MoS-Chandrasekhar/11-08-2023-487494",
            "clean_url": "businessworld.in",
            "excerpt": "The production generated under the scheme has already reached Rs 3,30,612 crore, and exports have surged to Rs 1,56,051 crore, , PLI scheme, MoS Rajeev Chandrasekhar",
            "summary": "As of June 2023, the PLI scheme has drawn investments worth Rs 6,887 crore, already surpassing the initial target of Rs 5,488 crore set for the fiscal year 2023-24, revealed Minister of State for Electronics and IT Rajeev Chandrasekhar.\nThe Indian government's Production-Linked Scheme (PLI) for large-scale electronics manufacturing, designed to bolster the country's electronics sector and enhance its participation in the global electronics supply chain, has surpassed expectations by attracting significant investments and achieving impressive milestones, said Chandrasekhar.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1679106702_WfmoPC_rajeev_chandrasekhar.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "6a16cd333b9844d8929bb9c4f3b45eac"
        },
        {
            "title": "Zerodha gets final nod for AMC licence from Sebi",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/tech/startups/zerodha-gets-final-nod-for-amc-licence-from-sebi/articleshow/102654499.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "The Bengaluru-based brokerage will look to launch exchange traded funds to begin its AMC journey.",
            "summary": "ETtech\nNithin Kamath, founder & CEO, Zerodha\nStockbroking startup \nZerodha\n has received final approval from market regulator Sebi to launch its \nasset management company\n business, \nNithin Kamath\n, its chief executive, announced today.\nZerodha is launching its \nAMC\n business in partnership with Smallcase, a company which was incubated within Rainmatter, its in-house corporate fund. Earlier this year in April, both Zerodha and Smallcase had announced that they would form a joint venture to launch the \nZerodha AMC\n business.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654488,width-1070,height-580,imgsize-18632,overlay-ettech/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "81c6039f1a263a614e1f594654a8000f"
        },
        {
            "title": "Backing Rahul Yadav's 4B Networks was a mistake, says Info Edge's Sanjeev Bikhchandani",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/tech/technology/backing-4b-was-a-mistake-says-info-edges-sanjeev-bikhchandani/articleshow/102653977.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "The consumer internet group has initiated arbitration proceedings against its portfolio company 4B Networks, founded by Housing.com cofounder Rahul Yadav, after the startup failed to provide crucial…",
            "summary": "ETtech\nInfo Edge cofounder Sanjeev Bikhchandani\nInfo Edge\n cofounder Sanjeev Bikhchandani on Friday told analysts that backing \nRahul Yadav\n's \n4B Networks\n was a mistake. \"You can't write off Rs 288 crore, it was a mistake,\" he told analysts at the company's conference call for its quarterly financial update.The company's board on Friday discussed steps to tighten controls and mitigate risks associated with corporate governance of its portfolio investments, he added.The consumer internet group has initiated arbitration proceedings against its portfolio company 4B Networks, founded by Housing.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654138,width-1070,height-580,imgsize-23700,overlay-ettech/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "c98120bf34bd1843f2bd3bb6075db53c"
        },
        {
            "title": "5 Simple Indian bedtime drinks to fix sleep patterns and heal insomnia",
            "author": "Nibedita Roy",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://timesofindia.indiatimes.com/life-style/food-news/5-simple-indian-bedtime-drinks-to-heal-insomnia/photostory/102645135.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "Here are some classic bedtime blends, which are great for naturally fixing sleep patterns. These simple homemade blends surely deserve a try!",
            "summary": "Ashwagandha is an age-old herb known for its ability to reduce stress, anxiety, depressive symptoms to name a few. Preparing a blend of milk and ashwagandha can naturally help in inducing sleep. This is due to the amalgamation of Ashwagandha's adaptogenic properties combined with Tryptophan in milk, which helps in fixing sleep cycle.\n\nInstructions:\n\nSteep ashwagandha root or powder in warm milk for about 10 minutes. Strain and drink tea before bedtime.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "food",
            "country": "IN",
            "language": "en",
            "authors": "Nibedita Roy",
            "media": "https://static.toiimg.com/photo/102646000.cms",
            "is_opinion": false,
            "twitter_account": "@timesofindia",
            "_score": null,
            "_id": "2bafb6e2b2df8863c524bbea6874a036"
        },
        {
            "title": "We Empower Remote India With Tech Driven Advisors Dhirendra Mahyavanshi Turtlemint",
            "author": "Rajany Pradhan",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/We-Empower-Remote-India-With-Tech-Driven-Advisors-Dhirendra-Mahyavanshi-Turtlemint/11-08-2023-487497",
            "clean_url": "businessworld.in",
            "excerpt": "In an interview with BW Businessworld, Turtlemint's Co-Founder & CEO, Dhirendra Mahyavanshi, talks about empowering insurance access and transforming communities , , Turtlemint, Dhirendra Mahyavanshi,…",
            "summary": "In an exclusive interview, Dhirendra Mahyavanshi, the Co-Founder and CEO of Turtlemint, discusses the journey of Turtlemint in revolutionising the insurance industry in India. With a mission to enhance insurance penetration and empower individuals, Turtlemint has transformed the insurance ecosystem. Mahyavanshi elaborates on the challenges faced and strategies employed, highlighting how Turtlemint has made insurance a lucrative career option for the youth. Excerpts:\nTurtlemint has empowered over 3.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Rajany Pradhan",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1691762284_KIkqhm_Turtlemint_Founder_Dhirendra.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "65de0f663885d6c9d2aa64ffc9842adc"
        },
        {
            "title": "1984 anti-Sikh riots: Jagdish Tytler granted 10 days for scrutiny of documents",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/delhi/1984-anti-sikh-riots-jagdish-tytler-granted-10-days-for-scrutiny-of-documents-534241",
            "clean_url": "tribuneindia.com",
            "excerpt": "A Delhi court on Friday granted 10 days to senior Congress leader and former Union Minister Jagdish Tytler to examine the CBI charge sheet and other documents in the Pul Bangash killings case related to the 1984 anti-Sikh riots.",
            "summary": "New Delhi, August 11\n\nA Delhi court on Friday granted 10 days to senior Congress leader and former Union Minister Jagdish Tytler to examine the CBI charge sheet and other documents in the Pul Bangash killings case related to the 1984 anti-Sikh riots.\n\nAdditional Chief Metropolitan Magistrate (ACMM) Vidhi Gupta Anand – who passed the order on an application moved by Tytler's counsel seeking two weeks for scrutiny of documents supplied to him by the court -- The ACMM will now take up the matter on August 21.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_158994579.JPG",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "0ac5ab0ff5fe2cfbf0485b8791e4c9e4"
        },
        {
            "title": "Star-Studded Affair: OMG Face of The Year Season 2 Shines Bright with Glitz and Glamour",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/star-studded-affair-omg-face-of-the-year-season-2-shines-bright-with-glitz-and-glamour20230811183353/",
            "clean_url": "aninews.in",
            "excerpt": "PNN Mumbai (Maharashtra) [India], August 11: OMG Face of The Year Season 2, the much-awaited India's First Digital talent hunt show organised by BlancKanvas Media, came to a dazzling close on a…",
            "summary": "PNN\nMumbai (Maharashtra) [India], August 11: \nOMG Face of The Year\n Season 2, the much-awaited India's First Digital talent hunt show organised by \nBlancKanvas Media\n, came to a dazzling close on a glittering Thursday evening in the presence of a galaxy of figures from the world of entertainment and glamour.\nThe second season of \nOMG Face of The Year\n, not only shattered all records but also provided an unmatched platform for emerging talent to showcase their talent and shine. Far from being merely a competition, the second season transformed itself into an exhilarating journey of aspirations and the determination to succeed despite all odds.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/ODdhNzkzMjMtODQ.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "a241a721cb684addbf2034521c9c869f"
        },
        {
            "title": "RBI Proposes To Introduce UPI Payments Through AI Conversations",
            "author": "BW Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/RBI-Proposes-To-Introduce-UPI-Payments-Through-AI-Conversations/11-08-2023-487412",
            "clean_url": "businessworld.in",
            "excerpt": "Unified Payments Interface (UPI) is India's mobile-based fast payment system, which facilitates customers to make round-the-clock payments instantly, using a Virtual Payment Address (VPA) created by…",
            "summary": "The Reserve Bank of India on Thursday proposed to introduce and enable UPI-based payments through AI-powered conversations.\nUnified Payments Interface (UPI) is India's mobile-based fast payment system, which facilitates customers to make round-the-clock payments instantly, using a Virtual Payment Address (VPA) created by the customer. It has become hugely popular for retail digital payments in India, and its adoption is increasing at a rapid pace.\nRBI Governor Shaktikanta Das, as part of its post-monetary policy meeting remarks earlier today, said it proposed to launch an innovative payment mode - \"Conversational Payments\" on UPI, that will enable users to engage in a conversation with an AI-powered system to initiate and complete transactions in a safe and secure environment.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1691508175_dSS3iX_GO5EL4U76RJFNLMDJ76TPU2GOY_1_.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "cac327b61729892e52df099e99c880c3"
        },
        {
            "title": "Puravankara Q1 Revenue at Rs. 323 Crores, up 50 Percent Y-o-Y; Pre-Sales of Rs. 1,126 Crores Delivers 119 Percent Growth",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/puravankara-q1-revenue-at-rs-323-crores-up-50-percent-y-o-y-pre-sales-of-rs-1126-crores-delivers-119-percent-growth20230811191931/",
            "clean_url": "aninews.in",
            "excerpt": "BusinessWire India Bengaluru (Karnataka) [India], August 11: Puravankara Limited (BSE: 532891), one of India's most trusted real estate players, announced its financial results today for the first…",
            "summary": "BusinessWire India\nBengaluru (Karnataka) [India], August 11: \nPuravankara Limited\n (BSE: 532891), one of India's most trusted \nreal estate players\n, announced its financial results today for the first quarter (Q1FY24) ending June 30, 2023.\nThe company recorded sales of Rs. 1,126 crores, an increase of 119% Y-o-Y. Sales volume for the quarter stood at 1.36 msft, up by 97% Y-o-Y with a strong collection of Rs. 696 crores (+52% Y-o-Y). Average price realisation increased by 11% to Rs. 8,227/sq ft during the quarter, up from Rs.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/MTIzYTc4NjktYzB.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "b4e60ff157a511dd8ae9c6e7fe11bf8e"
        },
        {
            "title": "Pulses sowing continues to lag as most regions face deficient rains",
            "author": "Pallavi Singhal",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.moneycontrol.com/news/economy/policy/pulses-sowing-continues-to-lag-as-most-regions-face-deficient-rains-11163591.html",
            "clean_url": "moneycontrol.com",
            "excerpt": "While the sown area for rice has increased by almost 5 percent, the sown area for pulse continues to lag with a decline of 8 percent",
            "summary": "The sowing of pulses continued to lag, with most regions of the country facing below-normal rainfall, in line with IMD predictions made for August.\nThe total sown area of pulses is down by almost eight percent as of August 11, year on year. Sowing was delayed due to patchy monsoon rainfall in producer states of Maharashtra and Karnataka in June. As rains picked up, while there was some increase in acreage, the overall numbers have continued to remain low.\nThe slow sowing of arhar, urad and moong together are causing the downfall.",
            "rights": "moneycontrol.com",
            "rank": 2753,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "Pallavi Singhal",
            "media": "https://images.moneycontrol.com/static-mcnews/2022/06/Farmer-sowing-seeds-770x433.png",
            "is_opinion": false,
            "twitter_account": "@moneycontrolcom",
            "_score": null,
            "_id": "9b918885f3ef68dd68cf47e4b54addc3"
        },
        {
            "title": "Gadar 2: Find Out How Many Crores Sunny Deol, Ameesha Patel Earn For Movie",
            "author": "Zee Media Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://zeenews.india.com/bollywood/gadar-2-find-out-how-many-crores-sunny-deol-ameesha-patel-earn-for-movie-2647800.html",
            "clean_url": "india.com",
            "excerpt": "The sequel to 2001 love saga Gadar: Ek Prem Katha has finally arrived in theatres and has amassed loved by the masses.",
            "summary": "New Delhi: \nAnil Sharma's much-awaited romantic drama 'Gadar 2: Ek Katha' starring Sunny Deol and Ameesha Patel in lead roles arrived in theatres today, i.e. August 11. The movie is a sequel to 2001 blockbuster 'Gadar' and has taken the internet by storm upon its release. Sunny, Ameesha and Utkarsh Sharma are reprising their roles from the first film. According to reports, the film has been made at a budget of Rs 75-80 crores and released in theatres today.  \nThe film, which has been helmed by Anil Sharma, focuses on Tara Singh, played by Sunny Deol, who returns to Pakistan to rescue his son Charanjeet Singh, who he believes is imprisioned by the army.",
            "rights": "india.com",
            "rank": 2337,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Zee Media Bureau",
            "media": "https://english.cdn.zeenews.com/sites/default/files/2023/08/11/1261214-gadar-2-sunny-deol-ameesha.jpg",
            "is_opinion": false,
            "twitter_account": "@zeenews",
            "_score": null,
            "_id": "e39d591d4d315d1b365376ad9fcdf664"
        },
        {
            "title": "Indian PM plans Greece visit later this month to expand strategic presence in Mediterranean",
            "author": "Dipanjan Roy Chaudhury",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/news/defence/indian-pm-plans-greece-visit-later-this-month-to-expand-strategic-presence-in-mediterranean/articleshow/102654493.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "Prime Minister Narendra Modi is expected to visit Greece this month to expand strategic footprints in the Mediterranean region. The last Indian Prime Minister to visit Greece was Indira Gandhi in…",
            "summary": "RBI Holds Rates, ups FY24 Inflation Forecast to 5.4%\nThe Reserve Bank of India (RBI) Thursday kept interest rates unchanged for the third straight review on expectations that inflation fuelled by high vegetable prices could reverse quickly, but asked lenders to set aside more cash as reserves to ensure surplus liquidity doesn't stoke prices further.\nCameras, Printers Could Face Import Curbs Now\nAfter making a licence mandatory for imports of personal computers and laptops, the government is looking at other products on which such curbs could be imposed such as cameras, printers, hard disks, parts of telephonic and telegraphic devices, said people aware of the matter.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "Dipanjan Roy Chaudhury",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654490,width-1070,height-580,imgsize-95882,overlay-etdefence/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "fefdc0eb46344d27a1ac210ec9c52e31"
        },
        {
            "title": "Zerodha AMC gets final nod, Vishal Jain to head as CEO: Nithin Kamath",
            "author": "Mohammed Uzair Shaikh",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.moneycontrol.com/news/business/zerodha-amc-gets-final-nod-announces-nithin-kamath-11163721.html",
            "clean_url": "moneycontrol.com",
            "excerpt": "\"We just received the final approval for the Zerodha AMC that we are building in partnership with smallcase,\" Nithin Kamat said.",
            "summary": "Zerodha has received the final regulatory nod to set up an asset management company (AMC), the discount broker's founder Nithin Kamath announced on August 11, adding that industry veteran Vishal Jain will head its operations as the chief executive officer (CEO).\n\"We just received the final approval for the Zerodha AMC that we are building in partnership with smallcase,\" Kamath posted on X, formerly known as Twitter. \"I'm also excited that Vishal Jain, who's been part of the entire passive investing journey in India from day 1, has joined us as a CEO to build the AMC,\" he added.",
            "rights": "moneycontrol.com",
            "rank": 2753,
            "topic": "business",
            "country": "IN",
            "language": "en",
            "authors": "Mohammed Uzair Shaikh",
            "media": "https://images.moneycontrol.com/static-mcnews/2023/06/Collage-Maker-23-Jun-2023-08-43-PM-4402-770x433.jpg",
            "is_opinion": false,
            "twitter_account": "@moneycontrolcom",
            "_score": null,
            "_id": "c9a82db455b7563952d2e90bea46fd95"
        },
        {
            "title": "BSF seizes medicines meant to be smuggled to Bangladesh",
            "author": "Uniindia News Service",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "http://www.uniindia.com/~/bsf-seizes-medicines-meant-to-be-smuggled-to-bangladesh/States/news/3029213.html",
            "clean_url": "uniindia.com",
            "excerpt": "Shillong, Aug 11 (UNI) Troopers of the Border Security Force (BSF) on Friday seized medicines worth over Rs. three lakh on the India-Bangladesh border in Meghalaya.",
            "summary": "BSF seizes medicines meant to be smuggled to Bangladesh\n\nShillong, Aug 11 (UNI) Troopers of the Border Security Force (BSF) on Friday seized medicines worth over Rs. three lakh on the India-Bangladesh border in Meghalaya.\n\nBSF spokesman said that the medicines worth rupees 3,74000 were seized from South Garo Hills district before smuggled to Bangladesh.\n\nThe seized medicines included Grifols injections, Amcoral tablets, Enterogermina injections, and many others, the BSF official said. The seized items have been handed over to Customs.",
            "rights": "uniindia.com",
            "rank": 31147,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Uniindia News Service",
            "media": "http://www.uniindia.com/cms/gall_content/LargePhoto//2023/8/2023_8$LargePhoto11_Aug_2023_11082023200207.jpg",
            "is_opinion": false,
            "twitter_account": "@Uniindia",
            "_score": null,
            "_id": "99071db34fd6e6f8d9099f905500ec1f"
        },
        {
            "title": "Russia and Ukraine trade aerial attacks as Zelenskyy makes another move against corruption",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/world/russia-and-ukraine-trade-aerial-attacks-as-zelenskyy-makes-another-move-against-corruption-534240",
            "clean_url": "tribuneindia.com",
            "excerpt": "Russia fired missiles at western Ukraine that killed an 8-year-old boy, local officials said, and drones that Russian officials blamed on the Ukrainian military targeted Moscow for a third straight day but reportedly didn't cause significant damage.",
            "summary": "Kyiv, August 11\n\nRussia fired missiles at western Ukraine that killed an 8-year-old boy, local officials said, and drones that Russian officials blamed on the Ukrainian military targeted Moscow for a third straight day but reportedly didn't cause significant damage.\n\nAlso Friday, Ukrainian President Volodymyr Zelenskyy announced the firing of all the heads of regional military draft boards, part of his crackdown on corruption since the outbreak of Russia's war in Ukraine more than 17 months ago.\n\nThe missile that killed the boy struck a house in western Ukraine's Ivano-Frankivsk region, about 100 kilometers (60 miles) from the Polish border, according to the office of Ukraine's prosecutor general.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "world",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_1663575682.JPG",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "b5a9fa1b008d026c0d141ced09a994ad"
        },
        {
            "title": "June Sees Industrial Production Growth Drop To Three-Month Low Of 3.7 Per Cent",
            "author": "Swarajya News Staff",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://swarajyamag.com/economy/june-sees-industrial-production-growth-drop-to-three-month-low-of-37-per-cent",
            "clean_url": "swarajyamag.com",
            "excerpt": "India's industrial production growth in June reached a three-month low of 3.7 per cent, primarily due to a weak performance by the manufacturing sector, as revealed through official data released on…",
            "summary": "India's industrial production growth in June \nreached\n a three-month low of 3.7 per cent, primarily due to a weak performance by the manufacturing sector, as revealed through official data released on Friday (11 August).\nThe Index of Industrial Production (IIP), which measures factory output growth, had a growth rate of 12.6 per cent in June 2022, mainly due to the lower base effect.\nIn March 2023, the IIP reached its previous low of 1.9 per cent. However, it then increased to 4.5 per cent in April and further to 5.",
            "rights": "swarajyamag.com",
            "rank": 25271,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "Swarajya News Staff",
            "media": "https://gumlet.assettype.com/swarajya/2022-02/e487b8b7-89bf-4f95-8c9a-646426a8a0af/Industrial_Policy.png?w=1200&auto=format%2Ccompress&ogImage=true",
            "is_opinion": false,
            "twitter_account": "SwarajyaMag",
            "_score": null,
            "_id": "6f20f321d687a1828ebacd1631603fae"
        },
        {
            "title": "Lulu group to raise $2.7 billion as its IPO plans gather steam",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/news/international/uae/lulu-group-to-raise-2-7-billion-as-its-ipo-plans-gather-steam/articleshow/102645930.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "Abu Dhabi-based hypermarket chain Lulu Group plans to raise Dh10bn ($2.7 bn) to refinance existing debt, before a possible IPO next year,, reports said. The financial injection will also enable the…",
            "summary": "RBI Holds Rates, ups FY24 Inflation Forecast to 5.4%\nThe Reserve Bank of India (RBI) Thursday kept interest rates unchanged for the third straight review on expectations that inflation fuelled by high vegetable prices could reverse quickly, but asked lenders to set aside more cash as reserves to ensure surplus liquidity doesn't stoke prices further.\nCameras, Printers Could Face Import Curbs Now\nAfter making a licence mandatory for imports of personal computers and laptops, the government is looking at other products on which such curbs could be imposed such as cameras, printers, hard disks, parts of telephonic and telegraphic devices, said people aware of the matter.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102649515,width-1070,height-580,imgsize-218796,overlay-economictimes/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "e4fe3b3f11d694277c9ee26d3f3d1132"
        },
        {
            "title": "UK announces new funding to deal with ‘pro-Khalistani extremism'",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/nation/uk-announces-new-funding-to-deal-with-pro-khalistani-extremism-534237",
            "clean_url": "tribuneindia.com",
            "excerpt": "The United Kingdom's Security Minister Tom Tugendhat has announced new funding of 95,000 pounds (around Rs 1 crore) to enhance Britain's capability to tackle \"pro-Khalistan extremism\".",
            "summary": "New Delhi, August 11\n\nThe United Kingdom's Security Minister Tom Tugendhat has announced new funding of 95,000 pounds (around Rs 1 crore) to enhance Britain's capability to tackle \"pro-Khalistan extremism\".\n\nThe British high commission said this in a readout on Tugendhat's three-day visit to India that began on Thursday.\n\nThe announcement on the new funding comes amid growing concerns in India over increasing activities of pro-Khalistani elements in the UK, especially after attacks on the Indian High Commission in London in March.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_200102417.jpg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "fb3974c339a2b8cda18b28bb7687ade7"
        },
        {
            "title": "India s Forex Holdings Decline To 601 4 Bn",
            "author": "BW Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/India-s-Forex-Holdings-Decline-To-601-4-Bn/11-08-2023-487492",
            "clean_url": "businessworld.in",
            "excerpt": "In addition, the country's gold reserves have seen a decrease of USD 224 million, amounting to USD 446.8 billion , , forex reserves",
            "summary": "India's foreign exchange reserves have witnessed a successive decline, with the latest data released by the Reserve Bank of India (RBI) revealing a drop of USD 2.41 billion to USD 601.453 billion for the week ending August 4. \nThis comes on the heels of a previous decrease of USD 3.2 billion, bringing the reserves to USD 603.87 billion for the week ending 28 July.\nAccording to the Weekly Statistical Supplement published by the RBI, the decline in foreign exchange reserves can be attributed to various contributing factors.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1592454004_Musgi3_978409_350.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "47828c38baef91d812a23ff3ae118b39"
        },
        {
            "title": "Twitterverse celebrates Sunny Deol's action-packed return in 'Gadar 2', lauds Akshay Kumar starrer 'OMG 2' as a 'fantastic film'",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/magazines/panache/twitterverse-celebrates-sunny-deols-action-packed-return-in-gadar-2-lauds-akshay-kumar-starrer-omg-2-as-a-fantastic-film/articleshow/102652599.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "'Gadar 2' and 'OMG 2' stormed theaters on Friday, triggering a wave of enthusiastic Twitter reactions. Sunny Deol's return in 'Gadar 2' garnered praise for its gripping narrative, while 'OMG 2'…",
            "summary": "Agencies\n'Gadar 2' and 'OMG 2' made a powerful double debut on the big screen, inviting an array of Twitter reactions that echoed with excitement. (Image Source: IMDB)\nIn a remarkable cinematic showdown, both \nSunny Deol\n starrer '\nGadar 2\n' and \nAkshay Kumar\n's '\nOMG 2\n' made their theatrical debut on Friday, triggering an enthusiastic wave of Twitter reactions from fans of both the stars.Amidst much anticipation and nostalgic fervour, 'Gadar 2' stormed into theatres, reuniting Sunny Deol and Ameesha Patel as the iconic Tara Singh and Sakina.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654402,width-1070,height-580,imgsize-168722,overlay-etpanache/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "81ffb2efac8fc90e7a1bb67f34559369"
        },
        {
            "title": "Delhi news: 24 students of MCD school fall sick due to gas leak in Naraina area",
            "author": "DNA Web Team",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.dnaindia.com/india/report-delhi-news-24-students-of-mcd-school-fall-sick-due-to-gas-leak-in-naraina-area-3055456",
            "clean_url": "dnaindia.com",
            "excerpt": "Officials from the civic health department rushed to the two hospitals and also to the school. The education department of the MCD is also on the job, the official added.",
            "summary": "Officials from the civic health department rushed to the two hospitals and also to the school. The education department of the MCD is also on the job, the official added.\nTwenty-four students of a municipal school in Delhi's Naraina area were taken ill and hospitalised on Friday following an alleged \"gas leak\" incident nearby, officials said.\nThe Aam Aadmi Party's MCD in-charge Durgesh Pathak said 15 students were admitted to Ram Manohar Lohia Hospital and they are doing fine.\n The rest were sent to the Acharya Shree Bhikshu Hospital, a senior official of the Municipal Corporation of Delhi told PTI.",
            "rights": "dnaindia.com",
            "rank": 2816,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "DNA Web Team",
            "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/08/11/2602999-school-ambulance.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "20cd3b7658998393fb4cae8764ca2901"
        },
        {
            "title": "TV channel editor arrested over 'inflammatory' post on Nuh violence",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/haryana/tv-channel-editor-arrested-over-inflammatory-post-on-nuh-violence-534235",
            "clean_url": "tribuneindia.com",
            "excerpt": "Sudarshan News editor has been arrested by police here over his alleged inflammatory posts on social media related to the communal violence in Nuh and adjoining districts in Haryana, an official said.",
            "summary": "Gurugram, August 11\n\nSudarshan News editor has been arrested by police here over his alleged inflammatory posts on social media related to the communal violence in Nuh and adjoining districts in Haryana, an official said.\n\nMukesh Kumar, the TV channel's managing editor, was arrested by the Gurugram Cyber Station East Police.\n\nSix people have been killed in the communal violence which erupted in Nuh on July 31 after a Vishva Hindu Parishad procession was attacked.\n\n#Gurugram #Nuh #Social Media",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "entertainment",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_1133426850.jpg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "5511aa92b9dcc11d4a8c7c647753521e"
        },
        {
            "title": "Microsoft bids farewell to Cortana on Windows 11, rolls out update to discontinue digital assistant",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/magazines/panache/microsoft-bids-farewell-to-cortana-on-windows-11-rolls-out-update-to-discontinue-digital-assistant/articleshow/102654296.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "Microsoft has ended support for its digital assistant, Cortana, on the Windows 11 platform, part of the company's renewed focus on AI and productivity tools.",
            "summary": "Agencies\nMicrosoft has discontinued Cortana digital assistant for Window 1. (Image Source: Microsoft)\nTech giant \nMicrosoft\n has officially bid farewell to its long-standing \ndigital assistant\n, \nCortana\n, on the Windows 11 platform, aligning with its strategic shift towards more accessible and efficient AI-driven solutions.\nAccording to \nThe Verge\n, this decision comes as part of Microsoft's ongoing strategic shift towards AI-driven solutions, aiming to provide users with enhanced productivity and efficiency tools.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654481,width-1070,height-580,imgsize-9996,overlay-etpanache/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "bd3d36b0c834700bc268e77bad8e7c52"
        },
        {
            "title": "Drug smuggler arrested in Punjab's Tarn Taran, 5 kg heroin seized",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/punjab/drug-smuggler-arrested-in-punjabs-tarn-taran-5-kg-heroin-seized-534234",
            "clean_url": "tribuneindia.com",
            "excerpt": "Punjab Police busted a cross-border drug smuggling racket and arrested an alleged smuggler after recovering five kilograms of heroin from his possession, a senior official said on Friday.",
            "summary": "Chandigarh, August 11\n\nPunjab Police busted a cross-border drug smuggling racket and arrested an alleged smuggler after recovering five kilograms of heroin from his possession, a senior official said on Friday.\n\nIn an intelligence-led operation, CI Amritsar recovered 5 Kg Heroin after arresting one person.\n\n\n\nAccused was actively involved in trans-border drug smuggling. FIR under NDPS Act is registered by #SSOC Amritsar and further Investigation ongoing to disrupt the network (1/2) pic.twitter.com/hX9cCk6Vop — DGP Punjab Police (@DGPPunjabPolice) August 11, 2023\n\nThe accused has been identified as Harpal Singh alias Bhala, a resident of village Lakhna in district Tarn Taran.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_285155739.jpg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "688661e1cd3d41f942e5b6876ef27f5c"
        },
        {
            "title": "ITC Undertaking Climate Risk Modelling To Sharp Target Adaptation Actions Sanjiv Puri",
            "author": "BW Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/ITC-Undertaking-Climate-Risk-Modelling-To-Sharp-Target-Adaptation-Actions-Sanjiv-Puri/11-08-2023-487496",
            "clean_url": "businessworld.in",
            "excerpt": "In the Company's 112th AGM address, Sanjiv Puri, Chairman and Managing Director, ITC shared his Vision on ITC: Nation First – Transforming for our Shared Tomorrows, , itc, Climate Risk Modelling,…",
            "summary": "Recognising the need to comprehensively address the challenge of global warming, a climate risk modelling exercise using advanced analytics was undertaken at a pan \nITC\n level, which was subsequently followed up with site-specific and agri value chain-specific assessments so as to sharp target adaptation actions. Based on such studies, appropriate site-specific interventions are being progressed.\nITC\n's Purposeful Adaptation Measures\nTo build resilience against the growing threat of extreme weather events, \nITC\n has initiated several purposeful adaptation measures to secure physical infrastructure and de-risk agri-value chains.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1691760945_rdrknQ_ezgif_sixteen_nine_101_1_.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "f23958016d76159aee3c850b692272f6"
        },
        {
            "title": "Prices of toned, full cream milk rose 9-10 per cent in June 2023 compared to 2022: Govt",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.tribuneindia.com/news/nation/prices-of-toned-full-cream-milk-rose-9-10-per-cent-in-june-2023-compared-to-2022-govt-534229",
            "clean_url": "tribuneindia.com",
            "excerpt": "Prices of toned and full-cream milk rose by 9 per cent and 10 per cent, respectively, in June this year compared to the same month last year, according to the government data.",
            "summary": "New Delhi, August 11\n\nPrices of toned and full-cream milk rose by 9 per cent and 10 per cent, respectively, in June this year compared to the same month last year, according to the government data.\n\nIn a written reply to Rajya Sabha, Fisheries, Animal Husbandry and Dairying Minister Parshottam Rupala said, 'As per information received from al Dairy Development Board (NDDB), the price of milk in the country has not increased drastically during the last three years'.\n\nIn June 2023, the price of toned milk was Rs 51.",
            "rights": "tribuneindia.com",
            "rank": 4959,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://englishtribuneimages.blob.core.windows.net/gallary-content/2023/8/2023_8$largeimg_2034567322.jpg",
            "is_opinion": false,
            "twitter_account": "&via=thetribunechd",
            "_score": null,
            "_id": "9a59ea9d7769a4ff6cdce1f75b1faa79"
        },
        {
            "title": "Government Proposes Capital Punishment For Mob Lynching In Major Revamp Of Criminal Laws",
            "author": "Abhay Rathore",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://swarajyamag.com/ideas/government-proposes-capital-punishment-for-mob-lynching-in-major-revamp-of-criminal-laws",
            "clean_url": "swarajyamag.com",
            "excerpt": "The Union government has announced significant changes to colonial-era criminal laws, aiming to introduce harsher punishments for crimes such as mob lynching and the rape of minors. Those involved in…",
            "summary": "The Union government has announced significant changes to colonial-era criminal laws, aiming to introduce harsher punishments for crimes such as mob lynching and the rape of minors. \nThose involved in such heinous crimes may face maximum punishment of death sentence.\nAdditionally, a new offence called \"endangering unity\" will replace sedition in the revised laws. \nUnion Home Minister Amit Shah has introduced three bills that will bring about significant changes in the legal system. \nThe Indian Penal Code of 1860 will be replaced by the Bharatiya Nyaya Sanhita, while the Code of Criminal Procedure will be replaced by the Bharatiya Nagarik Suraksha Sanhita.",
            "rights": "swarajyamag.com",
            "rank": 25271,
            "topic": "politics",
            "country": "IN",
            "language": "en",
            "authors": "Abhay Rathore",
            "media": "https://gumlet.assettype.com/swarajya/2021-09/311897d0-428d-47b0-a720-ec491e603739/yrxm2387ry743r7yr34.jpg?w=1200&auto=format%2Ccompress&ogImage=true",
            "is_opinion": false,
            "twitter_account": "SwarajyaMag",
            "_score": null,
            "_id": "ed9e557cd3b5b71a3e9e3f737b597707"
        },
        {
            "title": "Delhi Government Joins Rut3 and Rotary Club to Uplift Lives of PWDs with Cutting-Edge Wheelchair Technology",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/delhi-government-joins-rut3-and-rotary-club-to-uplift-lives-of-pwds-with-cutting-edge-wheelchair-technology20230811190836/",
            "clean_url": "aninews.in",
            "excerpt": "NewsVoir New Delhi [India], August 11: Rut3 Engineering Pvt. Ltd., a technology driven startup, unveils its first landmark initiative in cutting-edge wheelchair driven technology. In partnership with…",
            "summary": "NewsVoir\nNew Delhi [India], August 11: \nRut3 Engineering Pvt. Ltd\n., a \ntechnology driven startup\n, unveils its first landmark initiative in cutting-edge \nwheelchair driven technology\n. In partnership with Rotary Club and the Department of Social Welfare, Government of NCT of Delhi Rut3 have launched India's first ever suspension wheels-driven technology at the General Disability Camp. This groundbreaking technology is poised to revolutionize the independent living of \npersons with disabilities\n in India.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/MzhjNjc1NzMtMjM.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "9ef4f75a57e6e207e4a13f515846980b"
        },
        {
            "title": "Vidya Scholarship Program",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/vidya-scholarship-program-bridging-the-gap-between-dreams-and-reality20230811191457/",
            "clean_url": "aninews.in",
            "excerpt": "PNN Hyderabad (Telangana) [India], August 11: In a world where education is the key to unlocking boundless potential, we at Acumant are proud to announce the launch of the Vidya Scholarship Program.…",
            "summary": "PNN\nHyderabad (Telangana) [India], August 11: In a world where education is the key to unlocking boundless potential, we at Acumant are proud to announce the launch of the Vidya Scholarship Program. With a vision to empower talented and deserving students, this initiative aims to break down financial barriers and pave the way for a brighter future for exceptional individuals who aspire to make a difference in the world.Recognizing the pressing need to foster a generation of future leaders, innovators, and change-makers, the Vidya Scholarship Program is designed to offer significant support to students who demonstrate exemplary academic potential, remarkable leadership qualities, and a sincere desire to positively impact their communities.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/OTk3NWM4YTUtNzZ.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "bf924f661e80f5ea3199d2ce1ba2e033"
        },
        {
            "title": "Union Mutual Fund Unveils Fair Value Spectrum For Investors",
            "author": "BW Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/Union-Mutual-Fund-Unveils-Fair-Value-Spectrum-For-Investors/11-08-2023-487490",
            "clean_url": "businessworld.in",
            "excerpt": "Inevitably, there are phases in everything from macroeconomic factors, business sentiments, industry competitiveness and company situations that ultimately influence the trajectory of both fair values…",
            "summary": "'Our quanta mental investment approach is rigorous and long-term focused and has served us well. It is important to recognise, though, that long term is essentially a series of short terms,' Harshad Patwardhan, the newly appointed Chief Investment Officer said at Union Asset Management Company (Union AMC).\nHe said that inevitably, there are phases in everything from macroeconomic factors, business sentiments, industry competitiveness and company situations that ultimately influence the trajectory of both fair values and stock prices.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1691759154_f4jShr_3.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "af49f2409aeb3d037da06341c10a0cb3"
        },
        {
            "title": "Over 250 eminent citizens write to President, CJI for strong action against NewsClick",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/news/india/over-250-eminent-citizens-write-to-president-cji-for-strong-action-against-newsclick/articleshow/102654356.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "Over 250 eminent citizens, including former judges and ambassadors, have written to the President and Chief Justice of India calling for strong action against online news portal, NewsClick, which is…",
            "summary": "TIMESOFINDIA.COM\nNewsClick received funding from American billionaire Neville Roy Singham, who allegedly works closely with the Chinese government media machine.\nOver 250 eminent citizens, including former judges and ambassadors, have written to the President and Chief Justice of \nIndia\n calling for strong action against online news portal, \nNewsClick\n, which is alleged to have received dubious funds from American billionaire Neville Roy Singham to spread Chinese propaganda. Alleging that Indian taxpayers are being manipulated by fake news and subterfuge manufactured in China, the signatories to the letter said \"free press\" covertly funded by China has had a field day challenging our democracy.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654378,width-1070,height-580,imgsize-3964,overlay-economictimes/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "9c4379030c6d6b8171d2cdb2a6ad855f"
        },
        {
            "title": "Zydus Lifesciences Limited Reports Strong Operating Performance in Q1FY24",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/zydus-lifesciences-limited-reports-strong-operating-performance-in-q1fy2420230811191916/",
            "clean_url": "aninews.in",
            "excerpt": "BusinessWire India Ahmedabad (Gujarat) [India], August 11: Zydus Lifesciences Limited (including its subsidiaries/ affiliates hereafter referred to as \"Zydus\") announced its Q1FY24 results today.…",
            "summary": "BusinessWire India\nAhmedabad (Gujarat) [India], August 11: \nZydus Lifesciences Limited\n (including its subsidiaries/ affiliates hereafter referred to as \"Zydus\") announced its Q1FY24 results today. Zydus posts Q1FY24 revenues of Rs 5140 crores, a growth of 30% on a YoY basis. Profit After Tax of Rs 1087 crores was more than double of last year's base and grew by 110%. EBITDA saw a significant jump of 81% YoY at Rs1505 crores, with \nEBITDA margins\n of 29.3% vs 21% in corresponding previous quarter.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/ZDliZGVkMjgtODg.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "35cd8fdd5ef276cfaa86512cfc196284"
        },
        {
            "title": "AI Expert Da Sachin Sharma Unveils New Book, \"Prompt DOT AI: Mastering the Art of Creativity in the Age of AI\"",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/ai-expert-da-sachin-sharma-unveils-new-book-prompt-dot-ai-mastering-the-art-of-creativity-in-the-age-of-ai20230811192015/",
            "clean_url": "aninews.in",
            "excerpt": "PNN Mumbai (Maharashtra) [India], August 11: Author, AI enthusiast, and futurist Da Sachin Sharma proudly announce the release of his new book \"Prompt DOT AI: Mastering the Art of Creativity in the…",
            "summary": "PNN\nMumbai (Maharashtra) [India], August 11: Author, AI enthusiast, and futurist Da \nSachin Sharma\n proudly announce the release of his new book \"\nPrompt DOT AI: Mastering the Art of Creativity in the Age of AI\n\". The book explores the groundbreaking intersection of artificial intelligence and human creativity, revealing how innovative technology can empower individuals and organizations to leverage AI prompts for enriching creative outputs.\nIn this highly accessible and practical guide, Da Sachin introduces readers to the fascinating world of AI prompting - crafting effective prompts to guide AI tools in generating engaging and meaningful content.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/NTMzMTI3YjItYzV.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "8588a27463443f83949f387784a3d9ea"
        },
        {
            "title": "UPSC Civil Services Exam: Exhausted All Your Attempts? Dont Lose Heart, Check These 10 Best Career Options",
            "author": "Zee Media Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://zeenews.india.com/jobs-career/upsc-civil-services-exam-exhausted-all-your-attempts-dont-lose-heart-check-these-10-best-career-options-2647798.html",
            "clean_url": "india.com",
            "excerpt": "General candidates can appear for the UPSC Civil Services Exam 6 times till the age 32 years but if you have missed that opportunity then you can explore alternative career options that would put your…",
            "summary": "Hundreds of thousands of UPSC aspirants appear for the civil services exam each year but the dream of becoming an IAS only a few get to become IAS officer comes true only for a few. Candidates who fall in the general category can appear for the UPSC Civil Service Examination 6 times till the age of 32 years. In the relentless efforts of clearing the UPSC (Union Public Service Commission) exams, many aspirants exhaust the attempts but there are many alternative career options for the aspirants to shine and explore, some of which are listed as follows  \n1.",
            "rights": "india.com",
            "rank": 2337,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "Zee Media Bureau",
            "media": "https://english.cdn.zeenews.com/sites/default/files/2023/08/11/1261211-upsc-exam-2023-career-oprions.jpg",
            "is_opinion": false,
            "twitter_account": "@zeenews",
            "_score": null,
            "_id": "35d055cbc538a4ac0286b858222cc72d"
        },
        {
            "title": "Kyndryl and Microsoft Unveil Enterprise Generative AI Solutions on Microsoft Cloud",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/kyndryl-and-microsoft-unveil-enterprise-generative-ai-solutions-on-microsoft-cloud20230811191726/",
            "clean_url": "aninews.in",
            "excerpt": "PNN Bangalore (Karnataka) [India], August 11: Kyndryl(NYSE: KD), the world's largest technology infrastructure services provider, and Microsoft today announced a joint effort to enable the adoption of…",
            "summary": "PNN\nBangalore (Karnataka) [India], August 11: \nKyndryl\n (NYSE: KD), the world's largest technology infrastructure services provider, and \nMicrosoft\n today announced a joint effort to enable the adoption of enterprise-grade generative AI solutions for businesses on The \nMicrosoft\n Cloud. \nLeveraging the partnership's \nJoint Innovation Centers\n, Kyndryl's growing patent portfolio in data and AI, and its access to \nMicrosoft\n 365 Copilot, Azure OpenAI Service and \nMicrosoft\n Fabric, the two companies will rapidly design, develop and drive new generative AI innovations and solutions across their enterprises.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/OWYyZGU2MzktMDU.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "d2ed83e1f990a6bd02e62d68617408b4"
        },
        {
            "title": "NIA Hands Over 3 Bangladeshi Illegal Immigrants To Bengaluru Police, Identifies 24 More During Inquiries In UP Case",
            "author": "Nishtha Anushree",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://swarajyamag.com/news-headlines/nia-hands-over-3-bangladeshi-illegal-immigrants-to-bengaluru-police-identifies-24-more-during-inquiries-in-up-case",
            "clean_url": "swarajyamag.com",
            "excerpt": "Officials from the National Investigation Agency (NIA) successfully located and handed over three Bangladeshi nationals to the local police on Friday (11 August).These immigrants were found to be…",
            "summary": "Officials from the National Investigation Agency (NIA) successfully located and handed over three Bangladeshi nationals to the local police on Friday (11 August).\nThese immigrants were found to be residing illegally in Bengaluru's Bellandur area. The NIA team, initially investigating a case linked to Uttar Pradesh, uncovered the presence of these illegal immigrants during their inquiries. \nThe trio, identified as Khaleel Chaparasi, Abdul Khadir, and Mohammad Zaheed, were located during a search operation conducted on Monday.",
            "rights": "swarajyamag.com",
            "rank": 25271,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Nishtha Anushree",
            "media": "https://gumlet.assettype.com/swarajya/2021-08/2c61cb2d-dd42-44e7-a3c9-c6955696ef2a/swarajya_2020_08_fe829542_d5c5_465f_bc97_72dcb4b04872_nia.png?w=1200&auto=format%2Ccompress&ogImage=true",
            "is_opinion": false,
            "twitter_account": "SwarajyaMag",
            "_score": null,
            "_id": "5e80cc08aaf6cad5055cf12cd87ffa52"
        },
        {
            "title": "India plans welfare measures for gig workers ahead of elections",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://economictimes.indiatimes.com/news/india/india-plans-welfare-measures-for-gig-workers-ahead-of-elections/articleshow/102654235.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "The plan, part of the Social Security Code enacted in 2020, could include accident, health insurance and retirement benefits, said a senior government official with direct knowledge of the plan. Ahead…",
            "summary": "Reuters\nIn addition to the big-name companies, hundreds of other online platforms and the people they hire for piecemeal work would be affected, spanning services such as cab-sharing, retail, food, construction and finance.\nIndia plans to roll out \nwelfare measures\n for \"gig\" workers employed through platforms like \nAmazon\n, \nUber\n and India's \nZomato\n as Prime Minister \nNarendra Modi\n's government prepares for elections, government and trade union officials said. The plan, part of the Social Security Code enacted in 2020, could include accident, health insurance and retirement benefits, said a senior government official with direct knowledge of the plan.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "economics",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://economictimes.indiatimes.com/thumb/msid-102654272,width-1070,height-580,imgsize-160666,overlay-economictimes/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@EconomicTimes",
            "_score": null,
            "_id": "d54a10bedce1fb6824d8e641bf2438be"
        },
        {
            "title": "ISRO conducts drogue parachute deployment tests for Gaganyaan mission",
            "author": "Chethan Kumar",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://timesofindia.indiatimes.com/india/isro-conducts-drogue-parachute-deployment-tests-for-gaganyaan-mission/articleshow/102652475.cms",
            "clean_url": "indiatimes.com",
            "excerpt": "India News: BENGALURU: Isro Friday said that the Vikram Sarabhai Space Centre (VSSC) has conducted a series of drogue parachute deployment tests at the Rail Track.",
            "summary": "News\nIndia News\nISRO conducts drogue parachute deployment tests for Gaganyaan mission\nTrending\nAir India Logo\nParliament Monsoon Session\nChandrayaan 3 Photos\nIndian Penal Code\nSedition Law in India\nG20 Summit 2023\nChandrayaan 3 Moon Landing\nChandrayaan 3\nAir India Logo\nParliament Monsoon Session\nChandrayaan 3 Photos\nIndian Penal Code\nSedition Law in India\nG20 Summit 2023\nChandrayaan 3 Moon Landing\nChandrayaan 3\nAir India Logo\nParliament Monsoon Session\nChandrayaan 3 Photos\nIndian Penal Code\nSedit",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Chethan Kumar",
            "media": "https://static.toiimg.com/thumb/msid-102652751,width-1070,height-580,imgsize-61054,resizemode-75,overlay-toi_sw,pt-32,y_pad-40/photo.jpg",
            "is_opinion": false,
            "twitter_account": "@timesofindia",
            "_score": null,
            "_id": "e466045cc6d20aa4b8c2939079b3a519"
        },
        {
            "title": "Mindteck Reports Strong Q1 2023-24 Performance Marked by 5.3 Percent QoQ and 15.0 Percent YoY Growth",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/mindteck-reports-strong-q1-2023-24-performance-marked-by-53-percent-qoq-and-150-percent-yoy-growth20230811185041/",
            "clean_url": "aninews.in",
            "excerpt": "BusinessWire India Bengaluru (Karnataka) [India], August 11: Mindteck (India) Limited (BSE: 517344 and NSE: MINDTECK), the global engineering and technology solutions company with niche knowledge and…",
            "summary": "BusinessWire India\nBengaluru (Karnataka) [India], August 11: \nMindteck\n (India) Limited (BSE: 517344 and NSE: MINDTECK), the global engineering and \ntechnology solutions company\n with niche knowledge and expertise in the storage, medical device, semiconductor and \nanalytical instrument industries\n, reported its unaudited Financial Results for the first quarter ended June 30, 2023.\nConsolidated Revenue for the quarter ended June 30, 2023 stood at Rs. 93.41 crore, as against Rs. 88.74 crore for the previous quarter ended March 31, 2023 and Rs.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/MmE2Y2Q5NTYtNWQ.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "e41a3ea4df8aee5df397c5d77cc4c54a"
        },
        {
            "title": "Centre Gives Nod To Railway, Highway Projects Worth Rs 28,875 For Development",
            "author": "Bw Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/Centre-Gives-Nod-To-Railway-Highway-Projects-Worth-Rs-28-875-For-Development-/11-08-2023-487447",
            "clean_url": "businessworld.in",
            "excerpt": "Along with expanding commercial opportunities, the road and rail projects that span states like Odisha, Andhra Pradesh, Telangana, Maharashtra, and Karnataka will also provide jobs for the locals, , Centre government, roadways, highways, Projects",
            "summary": "The Interministerial National Planning Group has approved six railway and highway projects totaling Rs 28,875.16 crore in order to increase connectivity to diverse villages and important industrial business hubs across states and shorten travel times by avoiding crowded and densely inhabited areas.\n\nAlong with expanding commercial opportunities, the road and rail projects that span states like Odisha, Andhra Pradesh, Telangana, Maharashtra, and Karnataka will also provide jobs for the locals.\n\nThe list of projects includes Barbil-Nayagarh-Barsuan and Bhadrasahi- Kiriburu railway project which will see an investment of Rs 12,532.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1681394782_1AxcL3_615533_highway_project_100917_1_.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "8976b15f5a09b8bf923b81ecf0d1514c"
        },
        {
            "title": "Names of top L&T, Cognizant executives come to fore in corruption case investigation, ET Telecom",
            "author": "ET Telecom",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://telecom.economictimes.indiatimes.com/news/enterprise-services/names-of-top-lt-cognizant-executives-come-to-fore-in-corruption-case-investigation/102648373",
            "clean_url": "indiatimes.com",
            "excerpt": "Corruption Case: The case involves bribes allegedly paid to officials of Chennai Metropolitan Development Authority (CMDA), state housing, urban development department, as well as the then minister, during the construction of the IT company's 'KITS Campus' facility, ToI reported on August 11.",
            "summary": "The names of a number of top executives of L&T and Cognizant, both past and present, have come to the fore in the Vigilance and Anti-Corruption Unit's probe into an alleged bribery case.\n\n\n\nThe case involves bribes allegedly paid to officials of Chennai Metropolitan Development Authority (CMDA), state housing, urban development department, as well as the then minister, during the construction of the IT company's 'KITS Campus' facility, ToI reported on August 11.\n\n\n\nIt may be mentioned here that the said campus is located in the SEZ in Chennai and was constructed between 2011 and 2016.",
            "rights": "indiatimes.com",
            "rank": 296,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "ET Telecom,www.ETTelecom.com",
            "media": "https://etimg.etb2bimg.com/thumb/msid-102648373,imgsize-26950,width-1200,height=765,overlay-ettelecom/enterprise-services/names-of-top-lt-cognizant-executives-come-to-fore-in-corruption-case-investigation.jpg",
            "is_opinion": false,
            "twitter_account": "http://twitter.com/Ettelecom",
            "_score": null,
            "_id": "af4b28b9cbf205db813b162143ef40f2"
        },
        {
            "title": "Nykaa Records 27% Drop In Profit At Rs 4.5 Crore During Q1, EBITDA Surges 60%",
            "author": "Bw Online Bureau",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.businessworld.in/article/Nykaa-Records-27-Drop-In-Profit-At-Rs-4-5-Crore-During-Q1-EBITDA-Surges-60-/11-08-2023-487498",
            "clean_url": "businessworld.in",
            "excerpt": "Impressively, 80 per cent of this quarter's GMV contribution originated from existing customers, , nykaa, Q1 report",
            "summary": "Parent Company of Nykaa, FSN E-Commerce, Reports 27 per cent Dip in Q1 Net Profit FSN E-Commerce, the parent company of renowned fashion retailer Nykaa, faced a 27 per cent decline in net profit in the first quarter of the ongoing fiscal year. The net profit dropped to Rs 3.3 crore from Rs 4.5 crore in the same period last year. This reduction in profit can be attributed to a 23.5 per cent rise in expenditure, reaching Rs 1,418 crore compared to Rs 1,148 crore in the corresponding quarter of the previous year.",
            "rights": "businessworld.in",
            "rank": 9204,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "BW Online Bureau",
            "media": "https://static.businessworld.in/article/article_extra_large_image/1589278706_gwD1Dc_Nykaa_Logo_website.jpg",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "aac92a76d4216621a7444d0a55849149"
        },
        {
            "title": "Gadar 2 vs OMG 2: Sunny Deol's action bulldozes Akshay Kumar-starrer, to earn four times as much at box office",
            "author": "Abhimanyu Mathur",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.dnaindia.com/bollywood/report-gadar-2-vs-omg-2-sunny-deol-beats-akshay-kumar-at-box-office-pankaj-tripathi-anil-sharma-ameesha-patel-3055454",
            "clean_url": "dnaindia.com",
            "excerpt": "How the much-anticipated box office clash of Sunny Deol's Gadar 2 and Akshay Kumar's OMG 2 panned out.",
            "summary": "How the much-anticipated box office clash of Sunny Deol's Gadar 2 and Akshay Kumar's OMG 2 panned out.\nThe Independence Day weekend of 2023 saw the release of two big films. After Ranbir Kapoor-starrer Animal chose to postpone its release to later in the year, the weekend was left to two sequels – Sunny Deol's Gadar 2 and Akshay Kumar's OMG 2. Given that Gadar 2 was coming with a bigger pedigree, it was expected to do better. But many analysts felt that Akshay's stardom could give a boost to OMG 2 as well.",
            "rights": "dnaindia.com",
            "rank": 2816,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "Abhimanyu Mathur",
            "media": "https://cdn.dnaindia.com/sites/default/files/styles/half/public/2023/08/11/2602997-untitled-design-2023-08-11t185948.061.png",
            "is_opinion": false,
            "twitter_account": null,
            "_score": null,
            "_id": "6e1353f7792dab4fa4e733916c8b9cbe"
        },
        {
            "title": "Jailer And Vikram: Nelsons And Lokeshs Frittering Away A Cinematic Legacy",
            "author": "K Balakumar",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://swarajyamag.com/culture/jailer-and-vikram-nelsons-and-lokeshs-frittering-away-a-cinematic-legacy",
            "clean_url": "swarajyamag.com",
            "excerpt": "This is not a review of Jailer. The film, if you go by the word from Kollywood, is already on its way to being a big hit. Even a blockbuster, if you will. And there is a certain satisfaction to be had…",
            "summary": "This is not a review of \nJailer\n. \nThe film, if you go by the word from Kollywood, is already on its way to being a big hit. Even a blockbuster, if you will. \nAnd there is a certain satisfaction to be had when films of oldies like Rajinikanth and Kamal Haasan do well. When the world is hurtling inevitably towards all-things youth, the triumph of crusty veterans offers some comforting reassurance.\nJailer\n is filled with enjoyable montages of \nRajnisms\n that seem to hang out disparately for want of a hardy script and handy story.",
            "rights": "swarajyamag.com",
            "rank": 25271,
            "topic": "entertainment",
            "country": "IN",
            "language": "en",
            "authors": "K Balakumar",
            "media": "https://gumlet.assettype.com/swarajya/2023-08/0f6d538b-6f05-45a8-b3bf-960635ae8a63/Collage_Maker_11_Aug_2023_06_29_PM_8804.jpg?w=1200&auto=format%2Ccompress&ogImage=true",
            "is_opinion": false,
            "twitter_account": "SwarajyaMag",
            "_score": null,
            "_id": "51f4ddf8c9e24cf0aabf4b83eba42b85"
        },
        {
            "title": "Narayana enriches its IIT-JEE & NEET Coaching, Education Visionary Ashish Arora Joins as Chief Academic Officer",
            "author": "",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.aninews.in/news/narayana-enriches-its-iit-jee-amp-neet-coaching-education-visionary-ashish-arora-joins-as-chief-academic-officer20230811195451/",
            "clean_url": "aninews.in",
            "excerpt": "The Media People Hyderabad (Telangana) [India], August 11: The Narayana Educational Institutions, a pioneering name in education, proudly announced the appointment of Ashish Arora as its Chief…",
            "summary": "The Media People\nHyderabad (Telangana) [India], August 11: The \nNarayana Educational Institutions\n, a pioneering name in education, proudly announced the appointment of \nAshish Arora\n as its Chief Academic Officer. With an illustrious career spanning over three decades, Arora brings a wealth of expertise to his new role, having worked on positions of HoD, Academic Head and National Academic Head across the education landscape, including stints at Bansal Classes, Resonance, FIITJEE, Allen, and Unacademy.",
            "rights": "bruneinews.net",
            "rank": 8311,
            "topic": "news",
            "country": "IN",
            "language": "en",
            "authors": "",
            "media": "https://cdn.bignewsnetwork.com/NjJlNGE2N2QtYmF.jpg",
            "is_opinion": false,
            "twitter_account": "@bruneinewsnet",
            "_score": null,
            "_id": "2dd36b1133a3afb6541501a9837bcf70"
        },
        {
            "title": "RBL Bank's COO Pankaj Sharma steps down effective Sept 20",
            "author": "arna Banerjea",
            "published_date": "2023-08-11 15:00:00",
            "published_date_precision": "timezone unknown",
            "link": "https://www.moneycontrol.com/news/business/banks/rbl-banks-coo-pankaj-sharma-steps-down-effective-sept-20-11163661.html",
            "clean_url": "moneycontrol.com",
            "excerpt": "RBL Bank also stated that it has appointed Alok Rastogi as Head – Corporate Centre, who will now directly handle the operations function, apart from other responsibilities",
            "summary": "RBL Bank\n on August 11 informed the stock exchanges that Pankaj Sharma, Chief Operations Officer of the lender has tendered his resignation in order to pursue external opportunities.\nPost internal discussion held with Sharma, the bank has accepted his resignation and shall relieve him from his duties with effect from close of business hours on September 20, 2023, RBL Bank said in the regulatory filing.\nFurther, the lender also stated that it has appointed Alok Rastogi as Head – Corporate Centre, who will now directly handle the operations function, apart from other responsibilities.",
            "rights": "moneycontrol.com",
            "rank": 2753,
            "topic": "business",
            "country": "IN",
            "language": "en",
            "authors": "Aparna Banerjea",
            "media": "https://images.moneycontrol.com/static-mcnews/2019/10/RBL-Bank___-770x433.jpg",
            "is_opinion": false,
            "twitter_account": "@moneycontrolcom",
            "_score": null,
            "_id": "2e480ab79a53083017fdc5832444fc97"
        }
];
